上传文件接口支持自定义meta字段
wechatpay-apiv3/wechatpay-apache-httpclient pull request #103
Opened 2022-01-12 08:51 UTC by lianup

1. 增加uploadFile接口，支持自定义meta
2.  去除comment_on_pr.yml

2022-01-12 08:58 UTC, EmmetZC requested changes

2022-01-12 08:58 UTC, EmmetZC commented on src/main/java/com/wechat/pay/contrib/apache/httpclient/WechatPayUploadHttpPost.java
> +        public Builder withFile(String fileName, String meta, InputStream inputStream) {
我们的meta限制是json来的，传一个`map`或者是与 `json` 等价的结构进来吧。

2022-01-12 08:58 UTC, EmmetZC commented on src/main/java/com/wechat/pay/contrib/apache/httpclient/WechatPayUploadHttpPost.java
>          private String fileSha256;
已经不需要 `fileSha256` 这个成员变量了。

2022-01-12 08:58 UTC, EmmetZC commented on src/main/java/com/wechat/pay/contrib/apache/httpclient/WechatPayUploadHttpPost.java
>              if (uri == null) {
`uri` 的检查可以移到构造器里去不？

2022-01-12 09:38 UTC, EmmetZC commented on src/main/java/com/wechat/pay/contrib/apache/httpclient/WechatPayUploadHttpPost.java
> +        public Builder withFile(String fileName, String meta, InputStream inputStream) {
@lianup 提到Java中不存在一个公用的`Json`抽象，这里难以提供一个合理的类型来适配商户的各种实现，还是保持现状

2022-01-12 09:40 UTC, lianup commented on src/main/java/com/wechat/pay/contrib/apache/httpclient/WechatPayUploadHttpPost.java
>          private String fileSha256;
已删除

2022-01-12 09:40 UTC, lianup commented on src/main/java/com/wechat/pay/contrib/apache/httpclient/WechatPayUploadHttpPost.java
>              if (uri == null) {
已移动

2022-01-12 09:43 UTC, EmmetZC approved these changes
LGTM

2022-01-13 03:16 UTC, Eric-Lee-Handyman commented on src/main/java/com/wechat/pay/contrib/apache/httpclient/WechatPayUploadHttpPost.java
> +                throw new IllegalArgumentException("缺少上传图片接口URL");
用了File之后，不一定是图片了。

2022-01-13 03:16 UTC, Eric-Lee-Handyman commented on src/main/java/com/wechat/pay/contrib/apache/httpclient/WechatPayUploadHttpPost.java
> -            if (fileName == null || fileSha256 == null || fileInputStream == null) {
如果用户使用的时候，不先调用withImage、withFile的方法，直接调用这个build方法，这里会报什么错误？

2022-01-13 03:28 UTC, lianup commented on src/main/java/com/wechat/pay/contrib/apache/httpclient/WechatPayUploadHttpPost.java
> +                throw new IllegalArgumentException("缺少上传图片接口URL");
已修改注释

2022-01-13 03:28 UTC, lianup commented on src/main/java/com/wechat/pay/contrib/apache/httpclient/WechatPayUploadHttpPost.java
> +                throw new IllegalArgumentException("缺少上传图片接口URL");
已修改

2022-01-13 06:23 UTC, Eric-Lee-Handyman approved these changes

2022-01-13 06:54 UTC, xy-peng commented on src/main/java/com/wechat/pay/contrib/apache/httpclient/WechatPayUploadHttpPost.java
> +        }
为什么不实现成

```java
string meta = String.format("{\"filename\":\"%s\",\"sha256\":\"%s\"}", fileName, fileSha256);
return withFile(fileName, meta, inputStream);
```

2022-01-13 07:48 UTC, lianup commented on src/main/java/com/wechat/pay/contrib/apache/httpclient/WechatPayUploadHttpPost.java
> +        }
从逻辑的角度，withImage调用wtihFile来实现更合理。已修改

2022-01-13 08:01 UTC, xy-peng commented on src/main/java/com/wechat/pay/contrib/apache/httpclient/WechatPayUploadHttpPost.java
> +            if (meta == null || meta.isEmpty()) {
这些检查还是需要吧，除了fileSha256之外。开发者要是忘记调用`withFile()`或者`withImage()`就调用`build()`是要报错的哦。请再参考标准的builder实现。

2022-01-13 08:03 UTC, xy-peng commented on src/main/java/com/wechat/pay/contrib/apache/httpclient/WechatPayUploadHttpPost.java
> +            if (meta == null || meta.isEmpty()) {
现在虽然我们的设计meta就意味着有其他参数，但是未来可能放开了呢？

2022-01-13 08:25 UTC, lianup commented on src/main/java/com/wechat/pay/contrib/apache/httpclient/WechatPayUploadHttpPost.java
> +            if (meta == null || meta.isEmpty()) {
有道理。之前没有考虑未来放开的场景，已修改。

2022-01-13 08:51 UTC, xy-peng approved these changes

2022-01-13 08:52 UTC, merged