增加微信支付通知处理器
wechatpay-apiv3/wechatpay-apache-httpclient pull request #105
Opened 2022-01-19 12:03 UTC by lianup

2022-01-20 03:36 UTC, xy-peng requested changes

2022-01-20 03:36 UTC, xy-peng commented on src/main/java/com/wechat/pay/contrib/apache/httpclient/auth/WechatPayNotifyHandler.java
> +            throw new IllegalArgumentException("message为空");
另外，如果只能从 builder 构造，参数检查不是做过一遍了吗？很多参数都是自己可控的，难道你是想别人扩展NotifyHandler 吗

2022-01-20 03:36 UTC, xy-peng commented on src/main/java/com/wechat/pay/contrib/apache/httpclient/auth/WechatPayNotifyHandler.java
> +public class WechatPayNotifyHandler {
我觉得应该叫做 `NotificationHandler`

2022-01-20 03:36 UTC, xy-peng commented on src/main/java/com/wechat/pay/contrib/apache/httpclient/auth/WechatPayNotifyRequest.java
> +public class WechatPayNotifyRequest {
我担心这样直接暴露实现给开发者，不利于未来的扩展，就像图片上传一样。而是提供 interface，interface只包含验签所需要的字段，即

+ `serialno`
+ `message`
+ `signature`

而没有`timestamp`和`nonce`。

再针对接口提供实现会更好。

2022-01-20 04:07 UTC, lianup commented on src/main/java/com/wechat/pay/contrib/apache/httpclient/auth/WechatPayNotifyHandler.java
> +package com.wechat.pay.contrib.apache.httpclient.auth;
可以新建notify，放到notify下

2022-01-20 04:09 UTC, lianup commented on src/main/java/com/wechat/pay/contrib/apache/httpclient/auth/WechatPayNotifyHandler.java
> +public class WechatPayNotifyHandler {
移动到notify，前缀可去掉

2022-01-20 06:15 UTC, lianup commented on src/main/java/com/wechat/pay/contrib/apache/httpclient/auth/WechatPayNotifyRequest.java
> +public class WechatPayNotifyRequest {
可以修改为：
1. 增加Request接口，包括getSerialNumber()、getMessage()、getSignature()方法。
2. 增加NotifyRequest类，实现Request接口。

2022-01-20 06:19 UTC, lianup commented on src/main/java/com/wechat/pay/contrib/apache/httpclient/auth/WechatPayNotifyRequest.java
> +public class WechatPayNotifyRequest {
1还可以增加getBody()方法，也属于request的一部分。

2022-01-20 06:19 UTC, xy-peng commented on src/main/java/com/wechat/pay/contrib/apache/httpclient/auth/WechatPayNotifyHandler.java
> +public class WechatPayNotifyHandler {
用名词`notification` ？

2022-01-20 06:26 UTC, lianup commented on src/main/java/com/wechat/pay/contrib/apache/httpclient/auth/WechatPayNotifyHandler.java
> +public class WechatPayNotifyHandler {
好

2022-01-20 07:55 UTC, lianup commented on src/main/java/com/wechat/pay/contrib/apache/httpclient/auth/WechatPayNotifyHandler.java
> +            throw new IllegalArgumentException("message为空");
已修改参数校验

2022-01-20 07:55 UTC, lianup commented on src/main/java/com/wechat/pay/contrib/apache/httpclient/auth/WechatPayNotifyHandler.java
> +package com.wechat.pay.contrib.apache.httpclient.auth;
已修改

2022-01-20 07:56 UTC, lianup commented on src/main/java/com/wechat/pay/contrib/apache/httpclient/auth/WechatPayNotifyRequest.java
> +        parseBody();
已修改

2022-01-20 08:59 UTC, xy-peng requested changes
配套的readme呢？

2022-01-20 08:59 UTC, xy-peng commented on src/main/java/com/wechat/pay/contrib/apache/httpclient/notification/NotificationHandler.java
> +        return data;
这里返回一个完整的回调结构体，而不仅仅是加密的部分吧。还有id/type/summary等等对商户可能有价值信息。

2022-01-20 08:59 UTC, xy-peng commented on src/main/java/com/wechat/pay/contrib/apache/httpclient/notification/Request.java
> + * @author lianup
对外接口加一些注释？

2022-01-20 09:01 UTC, lianup commented
> 配套的readme呢？

打算在bump version时添加

2022-01-20 09:20 UTC, lianup commented on src/main/java/com/wechat/pay/contrib/apache/httpclient/notification/NotificationHandler.java
> +        return data;
可以返回一个parseResult，包括id、create_time、event_type、data（解密后的数据）、summary。

2022-01-20 13:05 UTC, lianup commented on src/main/java/com/wechat/pay/contrib/apache/httpclient/notification/Request.java
> + * @author lianup
已添加

2022-01-21 01:54 UTC, lianup commented on src/main/java/com/wechat/pay/contrib/apache/httpclient/notification/NotificationHandler.java
> +        return data;
已添加

2022-01-21 01:55 UTC, lianup commented on src/main/java/com/wechat/pay/contrib/apache/httpclient/auth/WechatPayNotifyRequest.java
> +public class WechatPayNotifyRequest {
已添加

2022-01-21 04:36 UTC, Eric-Lee-Handyman commented on src/main/java/com/wechat/pay/contrib/apache/httpclient/notification/ParseResult.java
> + * 包括：通知ID、通知创建时间、解密通知数据、通知类型、回调摘要
这些注释，可以放到对应的字段里边去

2022-01-21 04:36 UTC, Eric-Lee-Handyman commented on src/main/java/com/wechat/pay/contrib/apache/httpclient/notification/NotificationRequest.java
> +        public Builder withSerialNumber(String serialNumber) {
这个类的方法里不做参数是否为空的判断吗？

2022-01-21 04:36 UTC, Eric-Lee-Handyman commented on src/main/java/com/wechat/pay/contrib/apache/httpclient/notification/NotificationHandler.java
> +        return node.toString().replace("\"", "");
为什么要做这个处理？

2022-01-21 04:37 UTC, Eric-Lee-Handyman commented on src/main/java/com/wechat/pay/contrib/apache/httpclient/notification/NotificationHandler.java
> +    public Notification parse(Request request)
这里实际承担了验签 + parse的功能，命名上跟实际做的事情对不上。

2022-01-21 06:23 UTC, lianup commented on src/main/java/com/wechat/pay/contrib/apache/httpclient/notification/ParseResult.java
> + * 包括：通知ID、通知创建时间、解密通知数据、通知类型、回调摘要
已更新解析结果类。

2022-01-21 06:25 UTC, lianup commented on src/main/java/com/wechat/pay/contrib/apache/httpclient/notification/NotificationRequest.java
> +        public Builder withSerialNumber(String serialNumber) {
类本身没有任何业务规则，参数校验在NotificationHandler中。

2022-01-21 06:26 UTC, lianup commented on src/main/java/com/wechat/pay/contrib/apache/httpclient/notification/NotificationHandler.java
> +        return node.toString().replace("\"", "");
修改了反序列化的方式，此方法已去除。

2022-01-21 06:27 UTC, lianup commented on src/main/java/com/wechat/pay/contrib/apache/httpclient/notification/NotificationHandler.java
> +    public Notification parse(Request request)
解析包括了验签和解析请求体，可以理解验签是解析的其中一步。

2022-01-21 06:50 UTC, Eric-Lee-Handyman commented on src/main/java/com/wechat/pay/contrib/apache/httpclient/notification/NotificationHandler.java
> +    public Notification parse(Request request)
解析包体并不一定需要验签，验签跟解析回报没必然关系。

2022-01-21 06:55 UTC, lianup commented on src/main/java/com/wechat/pay/contrib/apache/httpclient/notification/NotificationHandler.java
> +    public Notification parse(Request request)
parse 可以理解为：解析微信支付通知。包含验签+解析包体。
如果觉得这样表意不清，可以修改为handle?

2022-01-21 07:06 UTC, xy-peng commented on src/main/java/com/wechat/pay/contrib/apache/httpclient/notification/NotificationHandler.java
> +    public Notification parse(Request request)
我觉得parse可以的，对于开发者而言，他就是要拿到内容。本质是从字符串反序列化内存中的结构体。只是有可能发生了解析失败或者验证失败，或者解密失败。

2022-01-21 07:25 UTC, Eric-Lee-Handyman commented on src/main/java/com/wechat/pay/contrib/apache/httpclient/notification/Notification.java
> +        public String toString() {
使用 ObjectMapper 来代替手写？

2022-01-21 07:25 UTC, Eric-Lee-Handyman commented on src/main/java/com/wechat/pay/contrib/apache/httpclient/notification/Notification.java
> +    public String toString() {
使用 ObjectMapper 来代替手写？

2022-01-21 07:25 UTC, Eric-Lee-Handyman commented on src/main/java/com/wechat/pay/contrib/apache/httpclient/notification/NotificationHandler.java
> +    private void validate(Request request) throws ValidationException {
这里应该返回一个bool值，验签失败的时候返回false，验签失败并不是一种exception。

2022-01-21 07:25 UTC, Eric-Lee-Handyman commented on src/main/java/com/wechat/pay/contrib/apache/httpclient/notification/NotificationHandler.java
> +        setDecryptData(notification);
notification里边的其他参数是否要做校验？
另外，这里是不是把步骤拆开比较合理，setDecryptData却返回了一个String，实际上你这里做了几个事情：
1. 解析body，拿到notification。
2. 解密notification里边的加密数据包。
3. 往notification设置解密后的数据包。

2022-01-21 07:25 UTC, Eric-Lee-Handyman commented on src/main/java/com/wechat/pay/contrib/apache/httpclient/notification/NotificationHandler.java
> +            String errorMessage = String.format("aes解密失败 apiV3Key[%s]， associatedData[%s] bodyNonce[%s] ciphertext[%s]",
Resource也有tostring方法，可以直接用？

2022-01-21 07:43 UTC, lianup commented on src/main/java/com/wechat/pay/contrib/apache/httpclient/notification/Notification.java
> +        public String toString() {
此处用到toString的地方为拼接错误信息，在错误中抛出，商户测试和使用时也可以直接用toString打印。

2022-01-21 07:46 UTC, lianup commented on src/main/java/com/wechat/pay/contrib/apache/httpclient/notification/NotificationHandler.java
> +    private void validate(Request request) throws ValidationException {
不抛出错误，如何让商户感知验证失败？

2022-01-21 08:04 UTC, lianup commented on src/main/java/com/wechat/pay/contrib/apache/httpclient/notification/NotificationHandler.java
> +        setDecryptData(notification);
1. notification里边的其他参数是否要做校验？
可以的。避免运行时商户调用直接返回运行时错误。
2. setDecryptData应该返回void，语义就是设置加密数据，我改下。

2022-01-21 08:41 UTC, lianup commented on src/main/java/com/wechat/pay/contrib/apache/httpclient/notification/NotificationHandler.java
> +            String errorMessage = String.format("aes解密失败 apiV3Key[%s]， associatedData[%s] bodyNonce[%s] ciphertext[%s]",
已修改。

2022-01-21 08:42 UTC, lianup commented on src/main/java/com/wechat/pay/contrib/apache/httpclient/notification/NotificationHandler.java
> +        setDecryptData(notification);
已修改。

2022-01-21 08:42 UTC, lianup commented on src/main/java/com/wechat/pay/contrib/apache/httpclient/notification/Notification.java
> +    public String toString() {
此处用到toString的地方为拼接错误信息，在错误中抛出，商户测试和使用时也可以直接用toString打印。

2022-01-21 08:53 UTC, Eric-Lee-Handyman commented on src/main/java/com/wechat/pay/contrib/apache/httpclient/notification/NotificationHandler.java
> +    private void validate(Request request) throws ValidationException {
可以在调用上层去抛这个错误而不是在这抛错，抛错不是你这个方法的目的。

2022-01-23 02:33 UTC, EmmetZC approved these changes

2022-01-23 03:08 UTC, xy-peng approved these changes

2022-01-23 03:11 UTC, merged