新增加解密方法传入transformation
wechatpay-apiv3/wechatpay-apache-httpclient pull request #136
Opened 2022-05-06 12:47 UTC by lddssxy

新增encrypt(String message, X509Certificate certificate, String transformation) 和 decrypt(String ciphertext, PrivateKey privateKey, String transformation)允许用户在调用加解密方法时传入特定的transformation, 使现有Java SDK可以兼容境外部分接口加解密使用的RSA/ECB/PKCS1Padding Transformation

2022-05-07 03:30 UTC, xy-peng commented on src/main/java/com/wechat/pay/contrib/apache/httpclient/util/PemUtil.java
> +
现在放置在这里有些突兀：

1. 看命名很难理解是从字符串读入证书，还是从本地路径加载。
2. 跟 `loadPrivateKey()` 没有成对。

证书的来源可能是本地文件、配置文件、网络、字符串，最初的设计没有设定具体的场景，所以只提供了基于流的方法。如果新增的方法只是用在 test 中，建议放到 test 函数中。

2022-05-07 03:34 UTC, xy-peng commented on src/test/java/com/wechat/pay/contrib/apache/httpclient/RsaCryptoTest.java
> +        String email = "lion@tencent.com";
不要包含可能任何公司有关的信息

2022-05-09 08:42 UTC, lianup commented on src/test/java/com/wechat/pay/contrib/apache/httpclient/RsaCryptoTest.java
> +    private static final String privateKey = "";
注释最好统一加上

2022-05-09 08:42 UTC, lianup commented on src/test/java/com/wechat/pay/contrib/apache/httpclient/RsaCryptoTest.java
> +    @Test
这个测试用例严格来说只是验证了加解密的可逆性，但没有验证加解密分别的正确性。
加密和解密，分开来写测试用例，是否更好一些？

2022-05-09 10:46 UTC, lddssxy commented on src/main/java/com/wechat/pay/contrib/apache/httpclient/util/PemUtil.java
> +
已从pemUtil中删除。

2022-05-09 10:47 UTC, lddssxy commented on src/test/java/com/wechat/pay/contrib/apache/httpclient/RsaCryptoTest.java
> +        String email = "lion@tencent.com";
已修改为Helloworld

2022-05-09 10:47 UTC, lddssxy commented on src/test/java/com/wechat/pay/contrib/apache/httpclient/RsaCryptoTest.java
> +    private static final String privateKey = "";
已修改

2022-05-09 10:49 UTC, lddssxy commented on src/test/java/com/wechat/pay/contrib/apache/httpclient/RsaCryptoTest.java
> +    @Test
这里调整为encryptWithTransformationTest 和 decryptWithTransformationTest两个测试。

2022-05-09 11:02 UTC, lianup commented on src/test/java/com/wechat/pay/contrib/apache/httpclient/RsaCryptoTest.java
> +        String text = "helloworld";
这里可以用加密`helloworld`得到的密文，跟后面加密得到的`encryptedText`判断是否相等，以此来证明加密的正确性。

2022-05-09 11:02 UTC, lianup commented on src/test/java/com/wechat/pay/contrib/apache/httpclient/RsaCryptoTest.java
> +        System.out.println("decrypted text: " + RsaCryptoUtil.decrypt(encryptedText, PemUtil.loadPrivateKey(privateKeyForDecrypt), transformation));
类似的，这里可以用密文的原数据与解密得到的明文判断是否相等，以此来证明解密的正确性。

2022-05-09 11:17 UTC, lddssxy commented on src/test/java/com/wechat/pay/contrib/apache/httpclient/RsaCryptoTest.java
> +        String text = "helloworld";
RSA每次加密生成的密文是不同的，无法通过提前存一个encryptedText判断相等来证明加密正确。

2022-05-09 11:21 UTC, lddssxy commented on src/test/java/com/wechat/pay/contrib/apache/httpclient/RsaCryptoTest.java
> +        System.out.println("decrypted text: " + RsaCryptoUtil.decrypt(encryptedText, PemUtil.loadPrivateKey(privateKeyForDecrypt), transformation));
这里因为用户需要替换掉encryptedText，所以并不能确保密文原数据是什么，所以这里输出出来比直接断言可能好一些。

2022-05-09 12:08 UTC, lianup commented on src/test/java/com/wechat/pay/contrib/apache/httpclient/RsaCryptoTest.java
> +        System.out.println("decrypted text: " + RsaCryptoUtil.decrypt(encryptedText, PemUtil.loadPrivateKey(privateKeyForDecrypt), transformation));
只要保证密文是正确的，是否给一个固定值就好

2022-05-09 12:48 UTC, lddssxy commented on src/test/java/com/wechat/pay/contrib/apache/httpclient/RsaCryptoTest.java
> +        System.out.println("decrypted text: " + RsaCryptoUtil.decrypt(encryptedText, PemUtil.loadPrivateKey(privateKeyForDecrypt), transformation));
也行，不过用户没法获取我们加密用的证书，所以依然需要替换encryptedText

2022-05-09 12:53 UTC, lddssxy commented on src/test/java/com/wechat/pay/contrib/apache/httpclient/RsaCryptoTest.java
> +        System.out.println("decrypted text: " + RsaCryptoUtil.decrypt(encryptedText, PemUtil.loadPrivateKey(privateKeyForDecrypt), transformation));
已修改哈

2022-05-09 15:00 UTC, xy-peng requested changes

2022-05-09 19:42 UTC, lddssxy commented on src/test/java/com/wechat/pay/contrib/apache/httpclient/RsaCryptoTest.java
> +        System.out.println("encrypted text: " + encryptedText);
这里是跟 RsaCryptoTest中之前的 encryptTest()保持一致。这里“有效单测”的解密方法是指用一种其他方式实现解密然后用它来验证么？

2022-05-09 20:35 UTC, lddssxy commented on src/test/java/com/wechat/pay/contrib/apache/httpclient/RsaCryptoTest.java
> +    @Test
已增加oaep对应的两个用例。

2022-05-09 20:35 UTC, lddssxy commented on src/test/java/com/wechat/pay/contrib/apache/httpclient/RsaCryptoTest.java
> +    private static final String privateKeyForDecrypt = ""; // 用于测试解密功能的私钥
已增加

2022-05-10 02:26 UTC, xy-peng commented on src/test/java/com/wechat/pay/contrib/apache/httpclient/RsaCryptoTest.java
> +        System.out.println("encrypted text: " + encryptedText);
之前就没有单元测试 😭 新代码的要求变高了。

> 指用一种其他方式实现解密然后用它来验证么？

对。

1. 用标准库加密再用`RsaCryptoUtil.decrypt()` 解密并断言结果。
2. 用 `RsaCryptoUtil.decrypt()` 验证 `RsaCryptoUtil.encrypt()`的结果。

2022-05-10 09:59 UTC, lddssxy commented on src/test/java/com/wechat/pay/contrib/apache/httpclient/RsaCryptoTest.java
> +        System.out.println("encrypted text: " + encryptedText);
这边采用如下方式调整：
1. 用标准库解密了RsaCryptoUtil.encrypt()并断言
2. 提供一个RsaCryptoUtil.encrypt()加密的text，再用RsaCryptoUtil.decrypt() 解密并断言。

2022-05-10 10:47 UTC, xy-peng approved these changes

2022-05-10 11:01 UTC, lianup approved these changes

2022-05-10 11:43 UTC, merged