代码可读性优化 & 语法简化
wechatpay-apiv3/wechatpay-apache-httpclient pull request #85
Opened 2021-10-31 12:54 UTC by Eric-Lee-Handyman

1. 使用腾讯JAVA代码规范重新格式化项目
2. 访问修饰符优化
3. 常量可读性优化
4. 注释使用 javadoc 风格
5. 使用 Java 7、8 的语法简化部分代码

2021-11-02 07:29 UTC, xy-peng requested changes

2021-11-02 07:29 UTC, xy-peng commented on .editorconfig
> +insert_final_newline = false
insert_final_newline = true ?

2021-11-02 07:29 UTC, xy-peng commented on .editorconfig
> +max_line_length = 100
max_line_length = 120 ?

2021-11-02 07:29 UTC, xy-peng commented on .editorconfig
> +continuation_indent_size = 4
ij_continuation_indent_size = 4 放到java配置中去？

2021-11-02 07:29 UTC, xy-peng commented on .editorconfig
> +[*]
root = true

避免被上层的.editorconfig影响

2021-11-02 07:29 UTC, xy-peng commented on .editorconfig
> +[*]
trim_trailing_whitespace = true

加一个这个吧，通用的都可以加上

2021-11-02 08:57 UTC, Eric-Lee-Handyman commented on .editorconfig
> +insert_final_newline = false
公司规范，默认文件配置。

2021-11-02 08:57 UTC, Eric-Lee-Handyman commented on .editorconfig
> +max_line_length = 100
公司规范，默认文件配置。

2021-11-02 08:58 UTC, Eric-Lee-Handyman commented on .editorconfig
> +continuation_indent_size = 4
公司规范，默认文件配置，java的是8

2021-11-02 09:05 UTC, Eric-Lee-Handyman commented on .editorconfig
> +continuation_indent_size = 4
java默认的是8，我误删了，补回去。

2021-11-02 13:07 UTC, lianup approved these changes

2021-11-03 03:45 UTC, xy-peng approved these changes

2021-11-03 07:16 UTC, merged