增加平台证书管理器
wechatpay-apiv3/wechatpay-apache-httpclient pull request #88
Opened 2021-11-16 09:34 UTC by lianup

2021-11-17 10:33 UTC, Eric-Lee-Handyman commented on src/main/java/com/wechat/pay/contrib/apache/httpclient/CertManagerSingleton.java
> +        executor.scheduleAtFixedRate(new Runnable() {
线程要重命名，jstack时才方便定位问题

2021-11-17 10:33 UTC, Eric-Lee-Handyman commented on src/main/java/com/wechat/pay/contrib/apache/httpclient/CertManagerSingleton.java
> +            public void run() {
定时器的入口会打log，用于确保有“定时执行”。

2021-11-17 10:33 UTC, Eric-Lee-Handyman commented on src/main/java/com/wechat/pay/contrib/apache/httpclient/CertManagerSingleton.java
> +            public void run() {
在最外层的run去执行catch，防止后期改动导致新的逻辑没有捕获。

2021-11-17 10:33 UTC, Eric-Lee-Handyman commented on src/main/java/com/wechat/pay/contrib/apache/httpclient/CertManagerSingleton.java
> +public class CertManagerSingleton {
提供close的接口来释放资源。

2021-11-17 10:33 UTC, Eric-Lee-Handyman commented on src/main/java/com/wechat/pay/contrib/apache/httpclient/CertManagerSingleton.java
> +    protected final ScheduledExecutorService executor = Executors.newSingleThreadScheduledExecutor();
建议使用自定义线程池，因为默认的newSingleThreadScheduledExecutor初始化的队列长度太大，在极端情况下会导致OOM，设计好拒绝策略。

2021-11-17 10:33 UTC, Eric-Lee-Handyman commented on src/main/java/com/wechat/pay/contrib/apache/httpclient/CertManagerSingleton.java
> +    protected Map<BigInteger, X509Certificate> deserializeToCerts(byte[] apiV3Key, String body)
这些方法可以考虑独立出去，这里跟证书更新的关系不是很大，这是一个反序列的工具。

2021-11-18 02:31 UTC, lianup commented on src/main/java/com/wechat/pay/contrib/apache/httpclient/auth/AutoUpdateCertificatesVerifier.java
> +    @Override
getLatestCertificate 属于 Verifier 的职责，需要放在里面。那么 AutoUpdateCertificatesVerifier 就要实现这个接口，但是内容可以返回空。

2021-11-18 03:01 UTC, lianup commented on src/main/java/com/wechat/pay/contrib/apache/httpclient/CertManagerSingleton.java
> +    public static CertManagerSingleton getInstance(Credentials credentials, byte[] apiV3Key, long minutesInterval) {
不能说违反设计原则，只是看起来像可以根据不同参数得到不同的实例。实际上，这里还是只能拿到一个实例，且参数只能被赋值一次。
可以根据stackoverflow中的建议，增加一个init方法来初始化。

2021-11-18 06:25 UTC, lianup commented on src/main/java/com/wechat/pay/contrib/apache/httpclient/CertManagerSingleton.java
> +    protected final ScheduledExecutorService executor = Executors.newSingleThreadScheduledExecutor();
这里的初始化队列长度有推荐的计算方式吗？

2021-11-24 14:15 UTC, Eric-Lee-Handyman commented on src/main/java/com/wechat/pay/contrib/apache/httpclient/cert/CertManagerSingleton.java
> +        if (this.credentials == null || this.apiV3Key.length == 0 || this.executor == null
参数合法性需要先判断

2021-11-24 14:20 UTC, Eric-Lee-Handyman commented on src/main/java/com/wechat/pay/contrib/apache/httpclient/auth/ScheduleUpdateCertificatesVerifier.java
> +        Verifier verifier = new CertificatesVerifier(certManagerSingleton.getCertificates());
不需要每次去new 一个 verifier，可以提供一个更新证书的方法。

2021-11-24 14:20 UTC, Eric-Lee-Handyman commented on src/main/java/com/wechat/pay/contrib/apache/httpclient/auth/ScheduleUpdateCertificatesVerifier.java
> +    public void beginScheduleUpdate(Credentials credentials, byte[] apiv3Key) {
这个改为init方法，把初始化相关操作放在这里，然后在构造函数去调用这个。

2021-11-25 06:38 UTC, Eric-Lee-Handyman commented on README.md
> +// 使用完毕建议调用停止定时更新方法，防止资源泄漏
这应该是一个option，如果开发者有需求就可以调用，否则，就没必要调用。
关闭后，就没法自动更新了，对于大多数情况来说是没必要的，让开发者自己决定。

2021-11-25 06:38 UTC, Eric-Lee-Handyman commented on src/test/java/com/wechat/pay/contrib/apache/httpclient/RsaCryptoTest.java
> +        // 使用完毕建议调用停止定时更新方法，防止资源泄漏
这应该是一个option，如果开发者有需求就可以调用，否则，就没必要调用。

2021-11-25 06:38 UTC, Eric-Lee-Handyman commented on src/test/java/com/wechat/pay/contrib/apache/httpclient/ScheduleUpdateVerifierTest.java
> +        verifier.stopScheduleUpdate();
这应该是一个option，如果开发者有需求就可以调用，否则，就没必要调用。

2021-11-25 08:28 UTC, xy-peng requested changes

2021-11-25 08:28 UTC, xy-peng commented on README.md
> +因为不需要传入微信支付平台证书，AutoUpdateCertificatesVerifier 在首次更新证书时**不会验签**，也就无法确认应答身份，可能导致下载错误的证书。
`ScheduleUpdateCertificatesVerifier` 笔误？忘记改了？

2021-11-25 08:28 UTC, xy-peng commented on README.md
> +参数说明：`apiV3Key`是String格式的API v3密钥。
> 参数说明：`apiV3Key`是String格式的API v3密钥。

这句话似乎没有必要，前面初始化的名词解释已经说明过了，现在可以去掉看看

2021-11-25 08:28 UTC, xy-peng commented on README.md
> +## 定时更新证书功能
这部分替换原有的自动更新证书的部分吧，不用保留「定时更新证书功能」的部分，在这里提一下即可

2021-11-25 08:28 UTC, xy-peng commented on src/main/java/com/wechat/pay/contrib/apache/httpclient/auth/Verifier.java
> +    X509Certificate getLatestCertificate();
接口新增加了要实现的方法，原有的扩展实现会不能用了，应该要加以说明

+ 理论上应该是增加 major 版本号，不过测试版本，至少增加 minor 吧
+ 评估是否需要独立的升级指引

2021-11-26 09:09 UTC, Eric-Lee-Handyman commented on README.md
> +若你正使用版本<`v0.3.0`的SDK，并准备升级为版本`v0.3.0`，请根据以下操作步骤进行。
这里写错了：若你正在使用以前版本的SDK

2021-11-26 09:09 UTC, Eric-Lee-Handyman commented on README.md
> +- 实现 getLatestCertificate 方法
这个可以放到 “使用 ScheduledUpdateCertificatesVerifier 替换 AutoUpdateCertificatesVerifier” 之后，通常使用方不会自己去实现这个

2021-11-26 09:09 UTC, Eric-Lee-Handyman commented on README.md
> +-  使用 ScheduledUpdateCertificatesVerifier 替换 AutoUpdateCertificatesVerifier
应该是先写：我是否需要关注这个步骤，再来看具体的步骤内容。

2021-11-26 12:35 UTC, xy-peng requested changes

2021-11-26 12:35 UTC, xy-peng commented on README.md
> +最新版本`0.3.0`重写了[定时更新平台证书功能](#定时更新平台证书功能)。原因参考[issue#66](https://github.com/wechatpay-apiv3/wechatpay-apache-httpclient/issues/66)。此次升级可能导致`Verifier`接口的兼容性问题，建议开发者以如下方式对代码进行更新。
版本`0.3.0`提供了更可靠的[定时更新平台证书功能](#定时更新平台证书功能)。若你使用了自动更新证书功能，推荐升级并使用新的`ScheduledUpdateCertificatesVerifier`替换`AutoUpdateCertificatesVerifier`。

注：`Verifier`接口新增了`getLatestCertificate()`方法。若你通过实现`Verifier`接口自定义了验签器，升级后需实现该方法。

2021-11-26 12:35 UTC, xy-peng commented on README.md
> +替换`自动更新证书功能`。
感觉这个没必要说了

2021-11-29 07:27 UTC, xy-peng approved these changes

2021-11-29 08:46 UTC, Eric-Lee-Handyman commented on src/main/java/com/wechat/pay/contrib/apache/httpclient/constant/WechatPayHttpHeaders.java
> + *         Date: 2021/10/29
这个不该改？

2021-11-29 08:46 UTC, Eric-Lee-Handyman commented on src/main/java/com/wechat/pay/contrib/apache/httpclient/util/CertSerializeUtil.java
> +
相关author都加上

2021-11-29 08:46 UTC, Eric-Lee-Handyman commented on src/main/java/com/wechat/pay/contrib/apache/httpclient/cert/CertManagerSingleton.java
> + */
新类的author都加上

2021-11-29 08:59 UTC, lianup commented on src/main/java/com/wechat/pay/contrib/apache/httpclient/constant/WechatPayHttpHeaders.java
> + *         Date: 2021/10/29
需要改，否则gradle报错。

2021-11-29 09:24 UTC, Eric-Lee-Handyman approved these changes

2021-11-29 09:27 UTC, merged