增加github action yaml
wechatpay-apiv3/wechatpay-apache-httpclient pull request #90
Opened 2021-12-03 13:10 UTC by lianup

2021-12-05 02:54 UTC, xy-peng requested changes
另外，还建议加上Java8/Java11的build测试检测

2021-12-05 02:54 UTC, xy-peng commented on .github/workflows/main.yml
> +      - name: Grant execute permission for gradlew
这一步没有必要吧

```bash
sh ./gradlew
```

2021-12-05 02:54 UTC, xy-peng commented on .github/workflows/main.yml
> +        uses: actions/setup-java@v1
为什么不用setup-java@v2 ?
建议指定好distribution，建议使用 11。相关的细节明确透明会有利于开发者使用。

2021-12-05 02:54 UTC, xy-peng commented on .github/workflows/main.yml
> +          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
key带上Java版本？免得未来切换的时候异常了

2021-12-05 02:54 UTC, xy-peng commented on .github/workflows/main.yml
> +        run: ./gradlew publish -Psigning.keyId=${{secrets.SIGNING_KEY_ID}} -Psigning.password=${{secrets.SIGNING_KEY_PASSWORD}} -Psigning.secretKeyRingFile=$(echo ~/.gradle/secring.gpg)
这部分能用环境变量吗？会不会因为历史记录而泄漏了相关信息？

2021-12-09 10:49 UTC, lianup commented on .github/workflows/main.yml
> +        run: ./gradlew publish -Psigning.keyId=${{secrets.SIGNING_KEY_ID}} -Psigning.password=${{secrets.SIGNING_KEY_PASSWORD}} -Psigning.secretKeyRingFile=$(echo ~/.gradle/secring.gpg)
应该不会。github action执行结果输出的secrets都是密文，不是明文

2021-12-10 02:47 UTC, lianup commented
> 另外，还建议加上Java8/Java11的build测试检测

gradle build 设置Java8，是否已经足够？

2021-12-10 10:35 UTC, xy-peng commented
> gradle build 设置Java8，是否已经足够？

java11加上吧，毕竟java8已经几乎EOL了

2021-12-15 03:42 UTC, lianup commented
> 
参考 https://securitylab.github.com/research/github-actions-preventing-pwn-requests/

2021-12-15 03:45 UTC, lianup commented
> > gradle build 设置Java8，是否已经足够？
> 
> java11加上吧，毕竟java8已经几乎EOL了

已添加。
另外，参考 https://securitylab.github.com/research/github-actions-preventing-pwn-requests/ ，从环境变量中获取secrets，再在命令中使用环境变量。但action一定会输出每个run步骤和环境变量（加密后）。

2021-12-17 11:19 UTC, xy-peng requested changes

2021-12-17 11:19 UTC, xy-peng commented on .github/workflows/main.yml
> +    tags: 'v*'
这个地方有点危险，push任意以v开头的就会命中。比如用release ？

2021-12-17 11:19 UTC, xy-peng commented on .github/workflows/main.yml
> +  build_1:
1. 是不是分成两个actions比较好，一个ci，一个cd
2. 可以用matrix，而不是写两个build_x

2021-12-17 11:19 UTC, xy-peng commented on .github/workflows/main.yml
> +          echo "$SIGNING_SECRET_KEY_RING_FILE" > ~/.gradle/secring.gpg.b64
可以不通过文件中转，能否在gralde.build里直接操作环境变量？通过文件，也存在泄漏的可能。

2021-12-22 02:31 UTC, lianup commented on .github/workflows/main.yml
> +  build_1:
分成了build和publish。

2021-12-22 02:33 UTC, lianup commented on .github/workflows/main.yml
> +          echo "$SIGNING_SECRET_KEY_RING_FILE" > ~/.gradle/secring.gpg.b64
已修改为环境变量形式，具体参考：https://docs.gradle.org/current/userguide/signing_plugin.html
Using in-memory ascii-armored OpenPGP subkeys

2021-12-22 02:34 UTC, lianup commented on .github/workflows/main.yml
> +    tags: 'v*'
增加check-tag规则，需符合语义化版本

2021-12-23 07:20 UTC, closed without merging