ScheduledUpdateCertificatesVerifier支持多商户
wechatpay-apiv3/wechatpay-apache-httpclient pull request #98
Opened 2021-12-28 09:22 UTC by lianup

2021-12-28 12:42 UTC, EmmetZC requested changes

2021-12-28 12:42 UTC, EmmetZC commented on src/main/java/com/wechat/pay/contrib/apache/httpclient/cert/CertManagerSingleton.java
>              executor.scheduleAtFixedRate(runnable, 0, minutesInterval, TimeUnit.MINUTES);
每个 `merchantId` 来初始化的时候都会设置 `minutesInterval`，不过似乎只有第一个有效？

需要修改一下设置更新周期的逻辑。

2021-12-28 12:42 UTC, EmmetZC commented on src/main/java/com/wechat/pay/contrib/apache/httpclient/cert/CertManagerSingleton.java
> +            initCertificates(merchantId, credentials, apiV3Key);
初始化失败的话（比如参数设置有误），是不是得有个机制告知调用者？

2021-12-28 12:42 UTC, EmmetZC commented on src/main/java/com/wechat/pay/contrib/apache/httpclient/auth/ScheduledUpdateCertificatesVerifier.java
> +    public void initCertManager(WechatPay2Credentials credentials, byte[] apiv3Key) {
为什么构造器和 `initCertManager` 都需要传入 `credentials`？
只在构造器中传一次会有什么问题呢？

2021-12-29 02:41 UTC, lianup commented on src/main/java/com/wechat/pay/contrib/apache/httpclient/auth/ScheduledUpdateCertificatesVerifier.java
> +    public void initCertManager(WechatPay2Credentials credentials, byte[] apiv3Key) {
initCertManager要用到credentials，如果只传一次，则credentials要作为ScheduledUpdateCertificatesVerifier的成员变量，是否没有必要？因为它只下载更新证书的时候用到，应该作为CertManagerSingleton的成员变量。

2021-12-29 02:46 UTC, lianup commented on src/main/java/com/wechat/pay/contrib/apache/httpclient/cert/CertManagerSingleton.java
> +            initCertificates(merchantId, credentials, apiV3Key);
initCertificates 调用 downloadAndUpdateCert，如果由参数错误或其他原因导致失败，会抛错，这样是否足够？

2021-12-29 03:02 UTC, EmmetZC commented on src/main/java/com/wechat/pay/contrib/apache/httpclient/auth/ScheduledUpdateCertificatesVerifier.java
> +    public void initCertManager(WechatPay2Credentials credentials, byte[] apiv3Key) {
这样的话 `initCertManager` 是不是应该是一个私有方法或者一个类方法。
构造器中已经传的参数在公开的成员方法中出现是很奇怪的事情，如果你让调用者传了两次，那保证两次传的内容一样由谁负责呢？

另外，如果要进行合理抽象的话，构造器使用 `(String mchid, Credentials cred, byte[] apiv3Key)` 会更合理一点，这样 `ScheduledUpdateCertificatedsVerifier`只依赖`Credentials`接口而不是具体实现。尽管你的实参还是 `WechatPay2Credentials`。

2021-12-29 03:17 UTC, EmmetZC commented on src/main/java/com/wechat/pay/contrib/apache/httpclient/cert/CertManagerSingleton.java
> +            initCertificates(merchantId, credentials, apiV3Key);
嗯，返回 `boolean` 或者抛错误都可以吧，这个取决于 Java 的编写习惯了。

2021-12-29 03:36 UTC, lianup commented on src/main/java/com/wechat/pay/contrib/apache/httpclient/auth/ScheduledUpdateCertificatesVerifier.java
> +    public void initCertManager(WechatPay2Credentials credentials, byte[] apiv3Key) {
有这样考虑过，如果构造器改为 (String mchid, Credentials cred, byte[] apiv3Key)，就无法向下兼容了

2021-12-29 03:37 UTC, lianup commented on src/main/java/com/wechat/pay/contrib/apache/httpclient/cert/CertManagerSingleton.java
> +            initCertificates(merchantId, credentials, apiV3Key);
嗯，当前的实现是这样的。

2021-12-29 03:43 UTC, EmmetZC commented on src/main/java/com/wechat/pay/contrib/apache/httpclient/auth/ScheduledUpdateCertificatesVerifier.java
> +    public void initCertManager(WechatPay2Credentials credentials, byte[] apiv3Key) {
其实现在这样也是无法保证兼容的吧，之前开发者传入的可能是 `Credentials` 的一个自定义实现而不是 `WechatPay2Credentials`

2021-12-29 03:43 UTC, lianup commented on src/main/java/com/wechat/pay/contrib/apache/httpclient/auth/ScheduledUpdateCertificatesVerifier.java
> +    public void initCertManager(WechatPay2Credentials credentials, byte[] apiv3Key) {
对，但是自定义实现的毕竟是少数

2021-12-29 03:46 UTC, EmmetZC commented on src/main/java/com/wechat/pay/contrib/apache/httpclient/cert/CertManagerSingleton.java
> +            initCertificates(merchantId, credentials, apiV3Key);
咦，我看你的代码，`downloadAndUpdateCert ` 已经已经Catch住了下载失败了呀，外层感知不到了吧。而且`status  code` 不对时也没有抛错误来着

2021-12-30 14:13 UTC, EmmetZC requested changes

2021-12-30 14:13 UTC, EmmetZC commented on src/main/java/com/wechat/pay/contrib/apache/httpclient/auth/ScheduledUpdateCertificatesVerifier.java
>          lock = new ReentrantLock();
不过总的来说，继续叫`SUCVerifier`倒是无伤大雅

2021-12-30 14:13 UTC, EmmetZC commented on src/main/java/com/wechat/pay/contrib/apache/httpclient/cert/CertManagerSingleton.java
>                  } else {
这里如果下载服务返回「签名有误」，是会抛出错误还是打个日志就走了？

2021-12-30 14:13 UTC, EmmetZC commented on src/main/java/com/wechat/pay/contrib/apache/httpclient/cert/CertManagerSingleton.java
> +                throw new Exception("商户数量超出限制");
按照 Java 对于 Exception 的分类：

这里是否应该给一个更具体的错误，以便商户开发者针对性捕获和恢复？
如果认为此时已经抵达不可接受的状态，是不是可以直接返回 `RuntimeException`（或其子类）？

2021-12-31 02:08 UTC, lianup commented on src/main/java/com/wechat/pay/contrib/apache/httpclient/cert/CertManagerSingleton.java
>                  } else {
这里的处理是打日志

2022-01-04 03:43 UTC, EmmetZC commented on src/main/java/com/wechat/pay/contrib/apache/httpclient/cert/CertificatesManager.java
> +            initCertificates(merchantId, credentials, apiV3Key);
如果因为验签失败导致初始化失败，此处不会抛错误出去

2022-01-04 06:27 UTC, lianup commented on src/main/java/com/wechat/pay/contrib/apache/httpclient/cert/CertificatesManager.java
> +            initCertificates(merchantId, credentials, apiV3Key);
已修改为抛出错误

2022-01-04 10:15 UTC, Eric-Lee-Handyman commented on src/main/java/com/wechat/pay/contrib/apache/httpclient/cert/CertificatesManager.java
> +        if (merchantCertificates == null || merchantCertificates.size() == 0 || apiV3Key.length == 0
这里细分拆开，其实merchantCertificates获取不到的时候就应该报错了，不应该再进行下边的操作了；
apiV3Key拿不到也不应该再去拿credentials；
这里要看下本身的逻辑顺序。

2022-01-04 10:15 UTC, Eric-Lee-Handyman commented on src/main/java/com/wechat/pay/contrib/apache/httpclient/cert/CertificatesManager.java
> +            throws WechatPayException {
为什么需要定义自己的exception?

2022-01-04 10:15 UTC, Eric-Lee-Handyman commented on src/main/java/com/wechat/pay/contrib/apache/httpclient/cert/CertificatesManager.java
> +    private void updateCertificates() throws WechatPayException {
downloadAndUpdateCert
initCertificates
updateCertificates

希望加一些注释，说明这三个方法的使用场景。

2022-01-04 10:15 UTC, Eric-Lee-Handyman commented on src/main/java/com/wechat/pay/contrib/apache/httpclient/cert/CertificatesManager.java
> +                verifier = new CertificatesVerifier(merchantCertificates);
看上去这个即使为空，也不影响？

2022-01-04 11:39 UTC, lianup commented on src/main/java/com/wechat/pay/contrib/apache/httpclient/cert/CertificatesManager.java
> +            if (certificate == null) {
返回false就好？也是代表着验证失败，在validator里面调用verify方法，如果返回false，会抛出验证失败异常

2022-01-04 11:47 UTC, lianup commented on src/main/java/com/wechat/pay/contrib/apache/httpclient/cert/CertificatesManager.java
> +        if (merchantCertificates == null || merchantCertificates.size() == 0 || apiV3Key.length == 0
这里的参数缺一不可，现在的逻辑是否也可以

2022-01-04 11:53 UTC, lianup commented on src/main/java/com/wechat/pay/contrib/apache/httpclient/cert/CertificatesManager.java
> +    protected static final int MAX_MERCHANT_COUNT = 720;
根据实际商户情况来看，是否有建议值？

2022-01-04 12:02 UTC, lianup commented on src/main/java/com/wechat/pay/contrib/apache/httpclient/cert/CertificatesManager.java
> +                verifier = new CertificatesVerifier(merchantCertificates);
已修改为：若merchantCertificates为空，则返回错误

2022-01-04 12:06 UTC, lianup commented on src/main/java/com/wechat/pay/contrib/apache/httpclient/cert/CertificatesManager.java
> +                verifier = new CertificatesVerifier(merchantCertificates);
这里应该改为使用DefaultVerifier，也不用获取和判断merchantCertificates。在verify过程出错则抛出错误即可。

2022-01-04 12:10 UTC, lianup commented on src/main/java/com/wechat/pay/contrib/apache/httpclient/cert/CertificatesManager.java
> +    private ConcurrentHashMap<String, Credentials> credentialsMap = new ConcurrentHashMap<>();
这个类名就叫Credentials，如果map再叫Credentials会有歧义？

2022-01-05 03:15 UTC, Eric-Lee-Handyman commented on UPGRADING.md
> +版本`0.4.0`提供了支持多商户号的[定时更新平台证书功能](#定时更新平台证书功能)。由于兼容性问题，若你使用了`ScheduledUpdateCertificatesVerifier`，请使用`CertificatesManager`替换：
版本`0.4.0`提供了支持多商户号的[定时更新平台证书功能](#定时更新平台证书功能)，不兼容版本`0.3.0`，若你使用了`ScheduledUpdateCertificatesVerifier`，请使用`CertificatesManager`替换：

2022-01-05 03:15 UTC, Eric-Lee-Handyman commented on README.md
> +版本>=`0.4.0`可使用 CertificatesManager.getVerifier(mchId) 得到的验签器替代默认的验签器。它会定时下载和更新商户对应的[微信支付平台证书](https://wechatpay-api.gitbook.io/wechatpay-api-v3/ren-zheng/zheng-shu#ping-tai-zheng-shu) （默认为1小时）。
mchId 保持跟代码里边的一致，merchantId

2022-01-06 03:09 UTC, lianup commented on src/main/java/com/wechat/pay/contrib/apache/httpclient/cert/CertificatesManager.java
> +        }
已在方法中捕获异常

2022-01-06 03:35 UTC, EmmetZC commented on UPGRADING.md
> ++                new PrivateKeySigner(mchSerialNo, merchantPrivateKey)), apiV3Key.getBytes(StandardCharsets.UTF_8));
这个示例代码的缩进有点问题

2022-01-06 04:00 UTC, lianup commented on UPGRADING.md
> ++                new PrivateKeySigner(mchSerialNo, merchantPrivateKey)), apiV3Key.getBytes(StandardCharsets.UTF_8));
已修改

2022-01-06 06:09 UTC, EmmetZC approved these changes

2022-01-06 08:17 UTC, Eric-Lee-Handyman commented on src/main/java/com/wechat/pay/contrib/apache/httpclient/cert/SafeSingleScheduleExecutor.java
> +    private static final int MAX_QUEUE_CAPACITY = 100;
超过这个容量，任务就会丢掉，使用者也不知道自己没更新到证书。

2022-01-06 10:07 UTC, Eric-Lee-Handyman approved these changes

2022-01-06 11:23 UTC, lianup commented on src/test/java/com/wechat/pay/contrib/apache/httpclient/CertificatesManagerTest.java
> +    public void setup() throws Exception {
catch的目的是处理资源泄漏、打日志排查问题，测试用例无此需求

2022-01-07 03:42 UTC, xy-peng commented
提供了证书管理器的话，要不要加入【在验签回调场景，如何获取证书】的说明？

2022-01-07 09:07 UTC, lianup commented
> 提供了证书管理器的话，要不要加入【在验签回调场景，如何获取证书】的说明？

因为通知回调和还是验证请求返回，获取平台证书的逻辑都是一样的，现在的示例就足够了

2022-01-07 13:10 UTC, xy-peng commented on src/main/java/com/wechat/pay/contrib/apache/httpclient/cert/CertificatesManager.java
> +            if (certificate == null) {
> 两种异常代表的含义不一样，这种证书找不到的情况，理论上不会出现。

如果是回调场景，坏人送一个错误的证书序列号，根本找不到，是可能的。所以这里抛RuntimeException有点不合适。

2022-01-07 13:14 UTC, xy-peng commented on src/main/java/com/wechat/pay/contrib/apache/httpclient/cert/CertificatesManager.java
> +        credentialsMap.put(merchantId, credentials);
是不是应该先`downloadAndUpdateCert()`成功，才加入map ？

2022-01-07 13:28 UTC, xy-peng commented on src/main/java/com/wechat/pay/contrib/apache/httpclient/cert/CertificatesManager.java
> +    public X509Certificate getLatestCertificate(String merchantId) {
能不能返回一个 Encryptor 而不是证书，这样商户不用了解证书而直接可以用来加密。未来国密的时候也能屏蔽掉证书的细节。

放未来的版本也行。

2022-01-07 13:32 UTC, xy-peng commented on src/main/java/com/wechat/pay/contrib/apache/httpclient/cert/CertificatesManager.java
> +            throw new IllegalStateException("请先调用putMerchant方法增加商户信息");
感觉这里是个普通的Exception，而不是RuntimeException，开发者应该显式的处理这里可能会出错的？

2022-01-07 13:33 UTC, xy-peng commented on src/main/java/com/wechat/pay/contrib/apache/httpclient/cert/CertificatesManager.java
> +        return latestCert;
没有找到证书的时候，返回null？抛出NoFound之类的异常是不是更合适？

2022-01-08 04:52 UTC, lianup commented on src/main/java/com/wechat/pay/contrib/apache/httpclient/cert/CertificatesManager.java
> +    public X509Certificate getLatestCertificate(String merchantId) {
放未来的版本中吧，先解决支持多商户的问题。

2022-01-10 02:56 UTC, lianup commented on src/main/java/com/wechat/pay/contrib/apache/httpclient/cert/CertificatesManager.java
> +        return latestCert;
已修改为抛出自定义NotFoundException

2022-01-10 02:56 UTC, lianup commented on src/main/java/com/wechat/pay/contrib/apache/httpclient/cert/CertificatesManager.java
> +            throw new IllegalStateException("请先调用putMerchant方法增加商户信息");
已修改参数校验和错误处理

2022-01-10 02:57 UTC, lianup commented on src/main/java/com/wechat/pay/contrib/apache/httpclient/cert/CertificatesManager.java
> +        credentialsMap.put(merchantId, credentials);
已调整顺序

2022-01-10 09:43 UTC, lianup commented on src/main/java/com/wechat/pay/contrib/apache/httpclient/cert/CertificatesManager.java
> +            if (certificate == null) {
已修改为return false

2022-01-10 09:44 UTC, lianup commented on src/main/java/com/wechat/pay/contrib/apache/httpclient/cert/CertificatesManager.java
> +        return latestCert;
增加校验证书合法性逻辑

2022-01-11 02:44 UTC, xy-peng approved these changes
LGTM

2022-01-11 02:49 UTC, merged